name: Testes Automatizados - Banco de Tintas

on:
  push:
    branches: ["main"]

jobs:
  selenium:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager mysql-connector-python

      - name: Rodar testes
        run: |
          cd automacao
          python -m tests.test_cadastro_tinta
